### ISSUE TITLE
Script is failing

### ISSUE THREAD

**Issue by almet** [Kinto/kinto-alwaysdata#15]
```Traceback (most recent call last):
  File "/home/almet/kinto/env/lib/python3.7/site-packages/pyramid/path.py", line 395, in _zope_dottedname_style
    found = getattr(found, n)
AttributeError: module 'kinto.plugins' has no attribute 'default_bucket'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/almet/kinto//app.wsgi", line 20, in <module>
    application = main(config.items('DEFAULT'), **dict(config.items('app:main')))
 File "/home/almet/kinto/env/lib/python3.7/site-packages/kinto/__init__.py", line 52, in main
    kinto.core.initialize(config, version=__version__, default_settings=DEFAULT_SETTINGS)
  File "/home/almet/kinto/env/lib/python3.7/site-packages/kinto/core/initialization.py", line 573, in initialize
    config.include("kinto.core", route_prefix=api_version)
  File "/home/almet/kinto/env/lib/python3.7/site-packages/pyramid/config/__init__.py", line 676, in include
    c(configurator)
  File "/home/almet/kinto/env/lib/python3.7/site-packages/kinto/core/__init__.py", line 208, in includeme
    config.include(app)
  File "/home/almet/kinto/env/lib/python3.7/site-packages/pyramid/config/__init__.py", line 642, in include
    c = self.maybe_dotted(callable)
  File "/home/almet/kinto/env/lib/python3.7/site-packages/pyramid/config/__init__.py", line 749, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/home/almet/kinto/env/lib/python3.7/site-packages/pyramid/path.py", line 335, in maybe_resolve
    return self._resolve(dotted, package)
  File "/home/almet/kinto/env/lib/python3.7/site-packages/pyramid/path.py", line 342, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/home/almet/kinto/env/lib/python3.7/site-packages/pyramid/path.py", line 397, in _zope_dottedname_style
    __import__(used)
  File "/home/almet/kinto/env/lib/python3.7/site-packages/kinto/plugins/default_bucket/__init__.py", line 14, in <module>
    from kinto.views.buckets import Bucket
  File "/home/almet/kinto/env/lib/python3.7/site-packages/kinto/views/buckets.py", line 4, in <module>
    from kinto.schema_validation import JSONSchemaMapping
  File "/home/almet/kinto/env/lib/python3.7/site-packages/kinto/schema_validation.py", line 2, in <module>
    from jsonschema import Draft7Validator, ValidationError, SchemaError, RefResolutionError, validate
ImportError: cannot import name 'Draft7Validator' from 'jsonschema' (/home/almet/kinto/env/lib/python3.7/site-packages/jsonschema/__init__.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
```

**Comment by almet** [comment]
For me the fix is:

```
/home/almet/kinto/env/bin/pip install git+https://github.com/Julian/jsonschema.git 
```

Related to https://github.com/Kinto/kinto/pull/1923/files.

Should go away as soon as the new minor kinto version is released.

**Comment by almet** [comment]
I cannot test right now, but as the new minor version is released, I'm closing this issue.
